//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phone_mvc.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phone_mvc.Common.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm điện thoại thành công..
        /// </summary>
        public static string AddPhoneSuccess {
            get {
                return ResourceManager.GetString("AddPhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi kết nối API..
        /// </summary>
        public static string ApiError {
            get {
                return ResourceManager.GetString("ApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt điện thoại thành công..
        /// </summary>
        public static string ApprovePhoneSuccess {
            get {
                return ResourceManager.GetString("ApprovePhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa điện thoại thành công..
        /// </summary>
        public static string DeletePhoneSuccess {
            get {
                return ResourceManager.GetString("DeletePhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu điện thoại đã tồn tại.
        /// </summary>
        public static string DuplicateModel {
            get {
                return ResourceManager.GetString("DuplicateModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên mẫu điện thoại không thể để trống..
        /// </summary>
        public static string EmptyModel {
            get {
                return ResourceManager.GetString("EmptyModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi máy chủ nội bộ..
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thương hiệu không tồn tại..
        /// </summary>
        public static string InvalidBrand {
            get {
                return ResourceManager.GetString("InvalidBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID không hợp lệ..
        /// </summary>
        public static string InvalidId {
            get {
                return ResourceManager.GetString("InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá phải lớn hơn 0..
        /// </summary>
        public static string InvalidPrice {
            get {
                return ResourceManager.GetString("InvalidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng tồn kho không thể âm..
        /// </summary>
        public static string InvalidStock {
            get {
                return ResourceManager.GetString("InvalidStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại không tồn tại..
        /// </summary>
        public static string PhoneNotFound {
            get {
                return ResourceManager.GetString("PhoneNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối điện thoại thành công..
        /// </summary>
        public static string RejectPhoneSuccess {
            get {
                return ResourceManager.GetString("RejectPhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip phải lớn hơn hoặc bằng 0..
        /// </summary>
        public static string SkipInvalid {
            get {
                return ResourceManager.GetString("SkipInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take phải lớn hơn 0..
        /// </summary>
        public static string TakeInvalid {
            get {
                return ResourceManager.GetString("TakeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật điện thoại thành công..
        /// </summary>
        public static string UpdatePhoneSuccess {
            get {
                return ResourceManager.GetString("UpdatePhoneSuccess", resourceCulture);
            }
        }
    }
}
